version: '3.8'

services:
  # Redis
  redis:
    image: redis
    container_name: redis
    restart: unless-stopped
    command: redis-server --requirepass fsoft@123
    volumes:
      - redis-data:/data
    ports:
     - 6379:6379

volumes:
  redis-data:
