#===============================================
#======  Using Python 3.9 build Imange =========
#===============================================

# pull official base image
# FROM python:3.9.5-slim-buster
FROM pytorch/pytorch:1.12.1-cuda11.3-cudnn8-runtime

# set work directory
WORKDIR /app

# set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# install dependencies
RUN pip install --upgrade pip


RUN apt-get update
RUN apt-get install ffmpeg libsm6 libxext6  -y

COPY ./requirements_gpu.txt /app/requirements_gpu.txt
RUN pip install -r requirements_gpu.txt


# copy project
COPY ./app/ /app/