#===============================================
#======  Using Python 3.9 build Imange =========
#===============================================

# pull official base image
# FROM pytorch/pytorch:1.12.1-cuda11.3-cudnn8-runtime
FROM nvcr.io/nvidia/pytorch:22.01-py3
ENV DEBIAN_FRONTEND=noninteractive

# set work directory
WORKDIR /app

# set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# install dependencies
RUN pip install --upgrade pip


RUN apt-get update
RUN apt-get install ffmpeg libsm6 libxext6  -y

COPY ./requirements_gpu.txt /app/requirements_gpu.txt
RUN pip install -r requirements_gpu.txt


# copy project
COPY ./worker/ /app/