version: '3.8'

services:
  api:
    build:
      context: ./api-module
      dockerfile: Dockerfile
    # image: api:latest
    container_name: api
    restart: unless-stopped
    command: sh -c "uvicorn main:app --host 0.0.0.0 --port 8081 --reload"
    volumes:
      - ./storages:/storages/
      - api-logs:/logs/
    ports:
      - 8081:8081

  consumer1:
    # build:
    #   context: ./kafka
    #   dockerfile: Dockerfile_gpu
    image: phamvanhanh6720/dl_gpu_consumer:latest
    environment:
      - CUDA_ID=0
    container_name: consumer1
    restart: unless-stopped
    command: sh -c "python main.py"
    volumes:
      - ./storages:/storages/
      -  consumer1-logs:/logs/
    depends_on:
      - api
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]

volumes:
  api-logs:
  consumer1-logs:

networks:
  default:
    external: true
    name: dl_network

